#!/bin/bash

versions=$(goup search)

filtered_versions=$(echo "$versions" | grep -v -E '(beta|rc)')
minor_versions=$(echo "$filtered_versions" | awk -F'.' '{ print $1"."$2 }' | sort -u)
latest_versions=('tip')


for minor_version in $minor_versions; do
    latest_version=$(echo "$filtered_versions" | grep -E "^$minor_version\." | sort -V | tail -1)
    echo "Latest version of $minor_version: $latest_version"
    latest_versions+=($latest_version)
done

# Print the array elements
# for element in "${latest_versions[@]}"; do
#     echo "$element"
# done

tmux new-session -d -s install-go

# Splitting the first pane horizontally
tmux split-window -h -t install-go:0

# Splitting the first pane vertically
tmux split-window -v -t install-go:0

# Splitting the second pane vertically
tmux split-window -v -t install-go:1

# commands=("goup install tip" "goup install 1.13" "goup install 1.14" "goup install 1.15" "goup install 1.16" "goup install 1.17" "goup install 1.18" "goup install 1.19")

for i in "${latest_versions[@]}"; do
    command="goup install $i"
    echo $command
    tmux select-pane -t install-go:0
    tmux split-window -v -t install-go:0
    tmux send-keys "$i" Enter
done

tmux select-pane -t install-go:0
tmux attach-session -t install-go


